language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.2
  - android-29
  - extra-android-m2repository
script:
  # - ./gradlew build jacocoTestReport assembleAndroidTest
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
